"""Adiciona modelos de Biblioteca Digital

Revision ID: 0f562f3dc40e
Revises: 8a80fd930c86
Create Date: 2025-09-15 15:59:27.457593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f562f3dc40e'
down_revision = '8a80fd930c86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria_material',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('material_digital',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('imagem_capa', sa.String(length=200), nullable=True),
    sa.Column('arquivo_pdf', sa.String(length=200), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('categoria_permissao_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categoria_material.id'], ),
    sa.ForeignKeyConstraint(['categoria_permissao_id'], ['categoria_usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('material_digital')
    op.drop_table('categoria_material')
    # ### end Alembic commands ###
