"""Adiciona nivel a CategoriaUsuario

Revision ID: 31a4d1ab1219
Revises: bcf08d882832
Create Date: 2025-09-15 12:57:10.889988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31a4d1ab1219'
down_revision = 'bcf08d882832'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categoria_usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nivel', sa.Integer(), nullable=False))
        batch_op.drop_column('nome')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categoria_usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nome', sa.VARCHAR(length=50), nullable=False))
        batch_op.drop_column('nivel')

    # ### end Alembic commands ###
