"""Adiciona modelos de Reuniao e Presenca

Revision ID: 8a80fd930c86
Revises: d4dae69dc80b
Create Date: 2025-09-15 15:37:48.109140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a80fd930c86'
down_revision = 'd4dae69dc80b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reuniao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('data_reuniao', sa.DateTime(), nullable=False),
    sa.Column('sala_jitsi', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sala_jitsi')
    )
    op.create_table('presenca',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('reuniao_id', sa.Integer(), nullable=False),
    sa.Column('data_presenca', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['reuniao_id'], ['reuniao.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('presenca')
    op.drop_table('reuniao')
    # ### end Alembic commands ###
