"""Criacao final do banco de dados

Revision ID: bcf08d882832
Revises: 
Create Date: 2025-09-15 10:36:38.861146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcf08d882832'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria_curso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('categoria_usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('contato', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('configuracao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chave', sa.String(length=50), nullable=False),
    sa.Column('valor', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chave')
    )
    op.create_table('produto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('categoria', sa.String(length=50), nullable=False),
    sa.Column('preco', sa.Float(), nullable=False),
    sa.Column('estoque', sa.Integer(), nullable=True),
    sa.Column('imagem_url', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=60), nullable=False),
    sa.Column('is_admin', sa.Boolean(), server_default='False', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('curso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=100), nullable=False),
    sa.Column('link_video', sa.String(length=200), nullable=False),
    sa.Column('imagem_thumbnail', sa.String(length=200), nullable=True),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('arquivo_anexo', sa.String(length=200), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('categoria_permissao_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categoria_curso.id'], ),
    sa.ForeignKeyConstraint(['categoria_permissao_id'], ['categoria_usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pedido',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('data_pedido', sa.DateTime(), nullable=False),
    sa.Column('valor_total', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_category',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('categoria_usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_usuario_id'], ['categoria_usuario.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('usuario_id', 'categoria_usuario_id')
    )
    op.create_table('item_pedido',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('preco_unitario', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedido.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item_pedido')
    op.drop_table('user_category')
    op.drop_table('pedido')
    op.drop_table('curso')
    op.drop_table('usuario')
    op.drop_table('produto')
    op.drop_table('configuracao')
    op.drop_table('cliente')
    op.drop_table('categoria_usuario')
    op.drop_table('categoria_curso')
    # ### end Alembic commands ###
