"""Adiciona modelo Aviso

Revision ID: d4799c300a6f
Revises: 0f562f3dc40e
Create Date: 2025-09-15 17:48:38.685147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4799c300a6f'
down_revision = '0f562f3dc40e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aviso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mensagem', sa.Text(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.Column('categoria_permissao_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['categoria_permissao_id'], ['categoria_usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('aviso')
    # ### end Alembic commands ###
