"""Adicionar coluna nome à categoria_usuario

Revision ID: d4dae69dc80b
Revises: 31a4d1ab1219
Create Date: 2025-09-15 13:44:04.862829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4dae69dc80b'
down_revision = '31a4d1ab1219'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categoria_usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nome', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categoria_usuario', schema=None) as batch_op:
        batch_op.drop_column('nome')

    # ### end Alembic commands ###
